version: '3.8'

services:
  web:
    build: .
    container_name: eduTech
    restart: always
    env_file:
      - .env.docker
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - my_network
    entrypoint: ["sh", "./entrypoint.sh"]
    command: ["gunicorn", "eduTech.wsgi:application", "--bind", "0.0.0.0:8000"]

  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    env_file:
      - .env.docker
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - my_network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /dev/null:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - my_network

volumes:
  pg_data:

networks:
  my_network:
    driver: bridge