# Generated by Django 3.0 on 2020-02-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200208_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_type',
            field=models.IntegerField(choices=[(1, 'Top-Menu'), (2, 'Main-Menu'), (3, 'Widget-Menu'), (4, 'Footer-Menu'), (5, 'Other-Menu')]),
        ),
    ]
