# Generated by Django 3.0 on 2020-02-16 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200208_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tags',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
